name: Build Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Podman
      run: sudo apt-get update && sudo apt-get install -y podman
    - name: Build Image
      run: podman build -t ghcr.io/akarinliu/wordpress-redis:latest . --no-cache
    - name: Login GitHub Account
      run: podman login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_TOKEN }}
    - name: Push Image
      run: podman push ghcr.io/akarinliu/wordpress-redis:latest